### ISSUE TITLE
delete a storage file throws error

### ISSUE THREAD

**Issue by BluegrassBelgium** [googleapis/nodejs-storage#1052]
Operating System version: Windows 7
Firebase Product : firebase-functions 3.3.0; firebase-admin 8.9.2
Node.js version: 12.13.1
NPM version: 6.12.1

I use firebase functions + express.js to serve as my backend API.
I use firebase-admin to manage pictures in google cloud storage. After a bit of a hassle I managed to get files stored in the bucket, but when I try to delete them, I get an error.

This is my code :

```js
export const deleteImage = (pictureItem: T, storePath: string): Promise => {

return new Promise<void>((reject, resolve) => {

    const extension = path.extname(pictureItem.pictureName as string);
    const fileNameWithoutExtension = path.basename(pictureItem.pictureName as string, extension);

    //StorageInfo is just a little class to manage info about the storage file
    const storageInfo = new StorageInfo(extension, fileNameWithoutExtension, storePath)

    const storageadmin = admin.storage();

    const storageBucket = admin.app().options.storageBucket as string;

    storageadmin.bucket(storageBucket).file(storageInfo.fullFileName)
        .get().then((f) =>
            storageadmin.bucket(storageBucket).delete(f)
                .then(() => {
                    resolve();
                }).catch((err) => {
                   //HERE I GET THE ERROR !!!
                    console.log('storageadmin delete err', err);
                    reject(err);
                })
        ).catch((err) => {
            console.log('storageadmin file err', err);
            reject(err);
        });
});
```

The error is :
```
RangeError: Maximum call stack size exceeded
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:27:31)
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:38:30)
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:38:30)
at value.map.v (/srv/node_modules/@google-cloud/projectify/build/src/index.js:29:32)
at Array.map ()
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:29:23)
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:38:30)
at replaceProjectIdToken (/srv/node_modules/@google-cloud/projectify/build/src/index.js:38:30)
at value.map.v (/srv/node_modules/@google-cloud/projectify/build/src/index.js:29:32)
at Array.map ()
```

At first, I also tried    
`   storageadmin.bucket(storageBucket).file(storageInfo.fullFileName).delete()`

but that gave me the error "delete undefined"

I reported this bug to firebase-admin, but they referred me to this repo...
So, here I am :-)

Thanks

Erwin

**Comment by BluegrassBelgium** [comment]
stupid me ! I switched the order of the returned Promise (reject, resolve) should be (resolve, reject) !
My my, I'm getting old !
