### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No such object

### ISSUE THREAD

**Issue by saran141998** [googleapis/nodejs-storage#1221]
```js
  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage();
  const myBucket=storage.bucket(process.env.bucketName);
  const file=myBucket.file('920221923111532725.pdf');
   
   file.download(async function(err, contents) {});


    file.download({
      destination: '/home/saravanan/Downloads'
    }, function(err) {});
    
    
    file.download().then(function(data) {
      const contents = data[0];
    });

 ```
While trying to download the file stored in firebase storage using above code I got the error
```
UnhandledPromiseRejectionWarning: Error: No such object: vintro-functions.appspot.com/920221923111532725.pdf
    at new ApiError (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespMessage (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:160:41)
    at Util.handleResp (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:134:76)
    at Duplexify.requestStream.on.on.res (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/storage/build/src/file.js:830:31)
    at Duplexify.emit (events.js:198:13)
    at DestroyableTransform.emit (events.js:198:13)
    at onResponse (/home/saravanan/Projects/download-test/functions/node_modules/retry-request/index.js:200:19)
    at PassThrough.<anonymous> (/home/saravanan/Projects/download-test/functions/node_modules/retry-request/index.js:152:11)
    at PassThrough.emit (events.js:203:15)
    at /home/saravanan/Projects/download-test/functions/node_modules/teeny-request/build/src/index.js:201:29
(node:9011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jkwlui** [comment]
This error came from the GCS API indicating the remote file (object) doesn't exist. Can you verify the object does exist in the bucket?

**Comment by shaffeeullah** [comment]
Closing due to inactivity. Please re-open if this is still an issue
