### ISSUE TITLE
Sample tests failing: "Permission denied on Cloud KMS key"

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#1254]
Example build: https://source.cloud.google.com/results/invocations/7ddfa1bd-9f06-4048-adbe-e9298d2f69cf/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-storage%2Fnode10%2Fsamples-test/log

```
{ Error: Permission denied on Cloud KMS key. Please ensure that your Cloud Storage service account has been authorized to use this key.
    at new ApiError (/tmpfs/src/github/nodejs-storage/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/tmpfs/src/github/nodejs-storage/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at Util.handleResp (/tmpfs/src/github/nodejs-storage/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at retryRequest (/tmpfs/src/github/nodejs-storage/node_modules/@google-cloud/common/build/src/util.js:434:22)
    at onResponse (/tmpfs/src/github/nodejs-storage/node_modules/retry-request/index.js:206:7)
    at res.text.then.text (/tmpfs/src/github/nodejs-storage/node_modules/teeny-request/build/src/index.js:219:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 403,
  errors:
   [ { message:
        'Permission denied on Cloud KMS key. Please ensure that your Cloud Storage service account has been authorized to use this key.',
       domain: 'global',
       reason: 'forbidden' } ]
```

@JustinBeckwith @jkwlui This seems to be failing on all PRs. It sounds like the service account needs more roles.

**Comment by fhinkel** [comment]
This is blocking a bunch of PRs from getting landed. Not sure if the permissions got changed or API changes happened.

**Comment by frankyn** [comment]
Thanks for the ping, I'm taking a look.

**Comment by frankyn** [comment]
Hi @stephenplusplus and @fhinkel,

I granted IAM role `roles/cloudkms.cryptoKeyEncrypterDecrypter` to the Cloud Storage robot service account for project: `long-door-651` (get it using [GetServiceAccount call](https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount/get?)).

Tests are now passing in https://github.com/googleapis/nodejs-storage/pull/1225. I'm not sure why they stopped working though.

Looking at Audit Logs to see if there were any permission changes. 
By chance were IAM permissions updated for the KMS keys used here?: https://github.com/googleapis/nodejs-storage/blob/ed1ec7b94d802063da0b870a10c2ca6433343ce0/.kokoro/setup-vars.sh#L23

**Comment by stephenplusplus** [comment]
Thanks @frankyn, safe to say this is resolved now.
