### ISSUE TITLE
Error when saving to Storage at Google Cloud Function: { Error: Could not refresh access token: Unsuccessful response status code…}

### ISSUE THREAD

**Issue by k1m0io** [googleapis/nodejs-storage#1288]
I've written my code some month ago, and now without changing something there is an error message when executing the same code. My code in a Google Cloud Function loads a picture from an AWS S3 bucket to google cloud and saves it in a bucket, which was actually working some month ago! My code is running node.js 10:

```js
            const tmpdir = os.tmpdir();
            const filePath = path.join(tmpdir, fileName);
            console.log(filePath);
            console.log(data);
            await writeFile(filePath, data.Body);

            const bucketName = "test";

            console.log('test1');
            let storage;
            if(!storage){
                storage = new Storage();
            }
            await storage.bucket(bucketName).upload(filePath, {
                gzip: false,
                metadata: {
                    cacheControl: "public, max-age=31536000"
                }
            });
            console.log('test2');
            console.log(`${filePath} uploaded to ${bucketName}.`);`
```
"test1" is printed in the logs, but "test2" not.

The error I get:
```js
function-138m28l2agh39{ Error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500
    at Gaxios._request (/srv/node_modules/gaxios/build/src/gaxios.js:85:23)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  response: 
   { config: 
      { url: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control',
        headers: [Object],
        retryConfig: [Object],
        params: [Object],
        responseType: 'text',
        timeout: 0,
        paramsSerializer: [Function: paramsSerializer],
        validateStatus: [Function: validateStatus],
        method: 'GET' },
     data: 'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control\n',
     headers: 
      { connection: 'close',
        'content-length': '260',
        'content-type': 'text/plain; charset=utf-8',
        date: 'Thu, 16 Jul 2020 14:25:37 GMT',
        'x-content-type-options': 'nosniff' },
     status: 500,
     statusText: 'Internal Server Error',
     request: 
      { responseURL: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control' } },
  config: 
   { url: 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control',
     headers: { 'Metadata-Flavor': 'Google' },
     retryConfig: 
      { noResponseRetries: 3,
        currentRetryAttempt: 3,
        retry: 3,
        httpMethodsToRetry: [Array],
        statusCodesToRetry: [Array] },
     params: 
      { scopes: 'https://www.googleapis.com/auth/iam,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/devstorage.full_control' },
     responseType: 'text',
     timeout: 0,
     paramsSerializer: [Function: paramsSerializer],
     validateStatus: [Function: validateStatus],
     method: 'GET' },
  code: '500' }
```
I have checked the permissions, they should be fine. How can it be that it code worked before and stopped working? Any suggestions what I should check?

**Comment by andrewsg** [comment]
It's unclear to me from the snippet and the error code where exactly the error is firing. Do you know what line of your code specifically is triggering the error?

**Comment by k1m0io** [comment]
Yes it's the line with `storage.bucket(bucketName).upload`.

These are the permissions of the function:

![image](https://user-images.githubusercontent.com/24543408/94025854-42388980-fdb9-11ea-8fbb-fa49a8ad17fb.png)

These are the permissions of the bucket:

![image](https://user-images.githubusercontent.com/24543408/94025899-51b7d280-fdb9-11ea-9197-ed011bf7adf5.png)


What I don't understand is, that it worked in January and when I tried to run it again some month later it stopped working without any changes. 

I have to say that I didn't use a key for the Storage API, is this mandatory now?

**Comment by shaffeeullah** [comment]
Hi @k1m0io, this should not be mandatory now. Are you still facing this issue? I am unable to reproduce with the code snippet provided. How are you calling this cloud function? What is the full definition of the function?

**Comment by shaffeeullah** [comment]
@k1m0io please reopen if you're still facing this issue

**Comment by 05hiteshbansal** [comment]
Here is my code Please help in resolving the issue


```import {getServices, renderMediaOnCloudrun} from '@remotion/cloudrun/client';
import {renderStillOnCloudrun} from '@remotion/cloudrun/client';
import { NextResponse } from "next/server";
export async function POST(req) {
    try {
        const {data}=await req.json();
        //const finalresult=async()=>{
            const services = await getServices({
                region: 'us-east1',
                compatibleOnly: true,
              });
               
              const serviceName = services[0].serviceName;
              console.log(services);
              const result = await renderMediaOnCloudrun({
                serviceName,
                region: 'us-east1',
                serveUrl: process.env.SERVE_URL,
                composition: 'VideoPlayer',
                inputProps: { },
                codec: 'h264',
              });
               
              if (result.type === 'success') {
                console.log(result.bucketName);
                console.log(result.renderId);
              }
     d=result;
    console.log(d);
    return NextResponse.json({
        success: true,
      });

    }

   catch (error) {
    return NextResponse.json({ message: error.message, status: 500 , success:false });
  }

}```
