### ISSUE TITLE
CONTENT_DOWNLOAD_MISMATCH

### ISSUE THREAD

**Issue by tw1t611** [googleapis/nodejs-storage#1596]
Hey, not sure if the bug is in regards to this package. Please close, if its not.

I ran
```bash
gsutil -m setmeta -r -h "Cache-control:public, max-age=259200" gs://ari-motors-2-uploads
```
and get the following error when downloading the images through `@google-cloud/storage`:
```bash
strapi_1    | RequestError: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.
strapi_1    |     at PassThrough.onComplete (/srv/app/node_modules/@google-cloud/storage/build/src/file.js:1044:43)
strapi_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
strapi_1    |   code: 'CONTENT_DOWNLOAD_MISMATCH'
strapi_1    | }
```
The file is later passed to sharp, which throw this error:
```bash
strapi_1    | [Error: Input buffer contains unsupported image format]
```

image download code:
```js
  const options = {
    destination: destFilename,
    // This will download the file, but in a wrong format
    // Sharp output: [Error: Input buffer contains unsupported image format]
    // validation: false,
  };

  try {
    await storage.bucket(bucketName).file(filepath).download(options);
  } catch (error) {
    console.log(error);
```
The exact same code did work before executing the command.
The command didn't cause an error when running it the first time about two months ago.

Example file (public url):
https://storage.googleapis.com/ari-motors-2-uploads/05_ARI_145_Seitenansicht_vorn_rechts_00b43df2d0/05_ARI_145_Seitenansicht_vorn_rechts_00b43df2d0.jpg

The downloaded files are safed as images with storage objects as content:
![image](https://user-images.githubusercontent.com/13353525/134149128-5c535d30-70a6-46a6-9d71-0858f908d802.png)
```bash
{
  "kind": "storage#object",
  "id": "ari-motors-2-uploads/ARI_458_Pritsche_L_Titelbilder_ef3149077f/ARI_458_Pritsche_L_Titelbilder_ef3149077f.png/1628772205883389",
  "selfLink": "https://www.googleapis.com/storage/v1/b/ari-motors-2-uploads/o/ARI_458_Pritsche_L_Titelbilder_ef3149077f%2FARI_458_Pritsche_L_Titelbilder_ef3149077f.png",
  "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/ari-motors-2-uploads/o/ARI_458_Pritsche_L_Titelbilder_ef3149077f%2FARI_458_Pritsche_L_Titelbilder_ef3149077f.png?generation=1628772205883389&alt=media",
  "name": "ARI_458_Pritsche_L_Titelbilder_ef3149077f/ARI_458_Pritsche_L_Titelbilder_ef3149077f.png",
  "bucket": "ari-motors-2-uploads",
  "generation": "1628772205883389",
  "metageneration": "3",
  "contentType": "image/png",
  "storageClass": "STANDARD",
  "size": "607105",
  "md5Hash": "y+ng2GK1Oh03UNcXQuxi8g==",
  "contentDisposition": "inline; filename=\"ARI 458 Pritsche LTitelbilder.png\"",
  "cacheControl": "public, max-age=259200",
  "crc32c": "H1fSVw==",
  "etag": "CP3fgabBq/ICEAM=",
  "timeCreated": "2021-08-12T12:43:25.885Z",
  "updated": "2021-09-21T07:22:12.574Z",
  "timeStorageClassUpdated": "2021-08-12T12:43:25.885Z"
}
```

**Comment by tw1t611** [comment]
Seems like this is happening:
https://storage.googleapis.com/download/storage/v1/b/ari-motors-2-uploads/o/ARI_458_Pritsche_XL_Titelbilder_a7298abe1a%2FARI_458_Pritsche_XL_Titelbilder_a7298abe1a.png?generation=1628772205873251&alt=media

**Comment by wednesday1889** [comment]
Same thing happening to me. I thought I was doing something wrong!

I tried using the older 5.0.0 version just to try it out and the issue is also happening there.

**Comment by stevenwaterman** [comment]
Have also been experiencing this issue this morning. Cloud functions that worked previously have stopped working after redeploying them without any change to the code.

**Comment by iPablo** [comment]
We are having the same problem. Yesterday it was working correctly and has stopped working with every App Engine redeployment

**Comment by A13k2** [comment]
We are seeing the exact same problem. 
Redeployed because of a different problem (us-central1 functions errored with `The request was aborted because there was no available instance.`).

Since then we are seeing this issue with a version of code that was previously working for a few days.
We have this problem on production and it basically makes our product unusable...

**Comment by dconwell** [comment]
Same problem here, it appears to break for both download() and createReadStream() but was working fine this weekend.

**Comment by WanderingBrooks** [comment]
> We are seeing the exact same problem.
> Redeployed because of a different problem (us-central1 functions errored with `The request was aborted because there was no available instance.`).
> 
> Since then we are seeing this issue with a version of code that was previously working for a few days.
> We have this problem on production and it basically makes our product unusable...

Similar problem where after redeploying a google cloud function now we can't write files to buckets with createWriteStream

**Comment by brunettdan** [comment]
Got the same problem. Setting **validation:false** option, will not throw the error, but the downloaded content is the metadata and not the file contents.

```
const [content] = await storage.bucket(bucketName).file(fileName).download({validation:false});
console.log(content.toString())
```

**Comment by A13k2** [comment]
Also tried `validation: false`, `validation: 'md5'` and `gzip: 'auto'`. Both of them didn't work

**Comment by A13k2** [comment]
It's working again for me. Didn't really change anything, just redployed sth that shouldn't have any effect on this.
So try it again or deploy and try again

**Comment by stevenwaterman** [comment]
Confirmed, redeployed and it's working now

**Comment by puzdrow** [comment]
Same here, working after redeployment

**Comment by tw1t611** [comment]
guess I can close this now. Ty guys. :)
