### ISSUE TITLE
File writestream errors with 408 when consuming slow readstream

### ISSUE THREAD

**Issue by surjikal** [googleapis/nodejs-storage#1622]
I am streaming data out of a slow API and into GCS.
This API is paginated, and it takes 5-20 minutes to get a response per page.

The first page of results get streamed into GCS, no problem, no matter how long the response takes.
But I can never get the second page to stream through, because a 408 error is returned.

I understand that maybe keeping the write stream alive for 5-20 minute between batches is a bit much...
But still, I'd expect this lib to re-open the upload on 408. Setting a timeout config doesn't seem to help.

I'd love some ideas on how I can work around this issue, ideally without writing anything to disk.

---

#### Environment details

  - OS: MacOS 11.16
  - Node.js version: 12.16.1
  - npm version: 6.14.11
  - `@google-cloud/storage` version: 5.14.3

#### Steps to reproduce

1. Create a write stream with `{ resumable: false }`
2. Create a read stream that pushes some data quickly, and then waits for 10-20 minutes, then pushes more data.
3. Get slapped with a 408

---

**Code to reproduce**

```javascript
import * as stream from 'stream';
import { Storage } from '@google-cloud/storage';

// Put your bucket here...
const BUCKET = 'PUT_BUCKET_HERE';
const FILE = 'tmp.txt';

// we set this to true whenever we hit an error,
// so that we don't wait for no reason...
let shouldPause = true;

async function pause(minutes = 20) {
    console.log('Pausing for', minutes, 'minutes...');
    while (minutes > 0 && shouldPause) {
        console.log('Remaining:', minutes);
        await new Promise(resolve => setTimeout(resolve, 1000 * 60));
        minutes = minutes - 1;
    }
}

async function* getDataFromSlowAPI() {
    for (const page of [0, 1, 2]) {
        console.log('--> Getting page:', page);
        if (page > 0) await pause();
        console.log('--> Received API response for page:', page);
        yield page.toString();
    }
}

async function main() {
    const storage = new Storage();

    console.log('writing to file...');
    const readstream = stream.Readable.from(getDataFromSlowAPI());

    const file = storage.bucket(BUCKET).file(FILE);
    const writestream = file.createWriteStream({ resumable: false });

    readstream
        .pipe(writestream)
        .on('error', function (err) {
            // 408 after a while...
            console.error('stream error:', err);
            shouldPause = false;
        })
        .on('finish', function () {
            console.log('stream finished');
        });
}

main();
```

**The 408 error, usually happens after 6 minutes**

```javascript
ApiError: Multiple errors occurred during the request. Please see the `errors` array for complete details.

    1. Request Timeout
    2. <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>408.</b> <ins>That’s an error.</ins>
  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>



    at new ApiError (.../@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:73:15)
    at Util.parseHttpRespMessage (.../@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:175:41)
    at Util.handleResp (.../@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:149:76)
    at .../@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:477:22
    at onResponse (.../@google-cloud/storage/node_modules/retry-request/index.js:228:7)
    at .../@google-cloud/storage/node_modules/teeny-request/src/index.ts:244:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 408,
  errors: [],
  response: PassThrough {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function],
      end: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    statusCode: 408,
    statusMessage: 'Request Timeout',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://storage.googleapis.com/upload/storage/v1/b/[redacted]/o?uploadType=multipart&name=tmp.txt'
    },
    body: '<!DOCTYPE html>\n' +
      '<html lang=en>\n' +
      '  <meta charset=utf-8>\n' +
      '  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n' +
      '  <title>Error 408 (Request Timeout)!!1</title>\n' +
      '  <style>\n' +
      '    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n' +
      '  </style>\n' +
      '  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n' +
      '  <p><b>408.</b> <ins>That’s an error.</ins>\n' +
      '  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      connection: 'close',
      'content-length': '1557',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Mon, 27 Sep 2021 23:46:52 GMT',
      'referrer-policy': 'no-referrer'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false
  }
}
```

**Comment by surjikal** [comment]
Tried with `{ resumable: true }` and got a `ECONNRESET` / `reason: socket hang up` after about 12 minutes.

**Comment by cojenco** [comment]
Hi @surjikal, since it may take up to 20 min to get a response, a few ways worth trying in this case is to config timeout or retryOptions totalTimeout to a very long time. `408 Request Timeout` is a retryable code in the library, so the issue could be mitigated by extending the timeout.

We also recommend making this a resumable upload. I see you've run into `ECONNRESET` after 12 min. I'm working with our team to look into that. Please let us know if one of the following configurations work for you. 

Explicitly configure a timeout as part of the CreateWriteStreamOptions
```
const writeStream = file.createWriteStream({resumable:false, timeout: 15000000});
// Set the HTTP request timeout in milliseconds. This option is not available for resumable uploads.
```


Pass the  custom retry configuration retryOptions into the storage constructor upon initialization
```
  const storage = new Storage({
    retryOptions: {
      autoRetry: true, 
      totalTimeout: 3000,
      // The total time in seconds between an initial request getting sent and its timeout. 
      idempotencyStrategy: IdempotencyStrategy.RetryAlways
    },
  });
```

**Comment by ddelgrosso1** [comment]
Hi @surjikal Thanks for bringing this to our attention. I just wanted to gather some more information. What is the size of the data being retrieved from the slow API? Since there is a long wait between data being received, is there a reason you want to use streams as opposed to writing each chunk individually and combining at the end?

**Comment by surjikal** [comment]
@cojenco thank you very much, I tried your suggestions along with various permutations but no luck.

resumable = false: with or without the tweaks, the sample code fails after 6 minutes consistently (with same error).
resumable = true: I get ECONNRESET consistently after 12 minutes. 

@ddelgrosso1 I unfortunately don't know the size of the API results in advance. Sometimes it's very small, sometimes it's too big to fit in my worker's memory. Usually I get results quickly, this is the first time I had an api that was slow enough to trigger this issue.

For the chunking solution, I would need to implement it as a Writable, just to keep things consistent with other output targets in my app. Something like this maybe (gsutil pseudocode):

```
BUCKET="your-bucket-here"
FILE="chunk-test/data.txt"

chunkfile="gs://${BUCKET}/${FILE}.tmp"
datafile="gs://${BUCKET}/${FILE}"

gsutil rm "$chunkfile" || true
gsutil rm "$datafile" || true

echo -n "" | gsutil cp - "$datafile"
for i in 1 2 3; do
    echo "$i" | gsutil cp - "$chunkfile"
    gsutil compose "$datafile" "$chunkfile" "$datafile"
done

gsutil cat "$datafile"
```

But I guess it could work like:

```

```

**Comment by ddelgrosso1** [comment]
Thanks for the information @surjikal. I am going to check around with some other people on the team and see if they have encountered anything similar in other library languages.

**Comment by ddelgrosso1** [comment]
Hi @surjikal after talking with some other members of the team, it appears that the behavior you are seeing would be expected. The server side is setup to close long living idle connections which would result in the 408 / ECONNRESET. I know you noted that it would not be possible to buffer these objects in memory first at full size but perhaps a suggestion would be to try and read smaller chunks and upload those to GCS and utilize a `combine` operation at the end.

**Comment by surjikal** [comment]
Thanks for the suggestion regarding combine. Makes sense. Also makes sense why this breaks for resumable = false.

I don't understand why resumable = true can't recover correctly though. It keeps track of the offset, and the actual upload link is valid for a week. Is it because the backend returns ECONNRESET, which is not in the list of retry-able errors?

I'll poke around gcs-resumable-upload too. Thanks for the help!

**Comment by surjikal** [comment]
@ddelgrosso1 do you think the latest version with its improvements to resumable upload fixes this issue? Or you think it's still better to fix it in user land?

**Comment by surjikal** [comment]
Very cool, will check it out!
