### ISSUE TITLE
Calling bucket exists throws Invalid bucket name error

### ISSUE THREAD

**Issue by meyerovb** [googleapis/nodejs-storage#1652]
Running nodejs 14 in google cloud function, bucket doesn't exist and i run this code:

const bucket = storage.bucket('mybucketname');
const [bucketExists] = await bucket.exists();

Get this error, should just be false
```
"Error: Invalid bucket name: 'mybucketname'
    at new ApiError (/workspace/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:73:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:208:38)
    at Util.handleResp (/workspace/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:149:117)
    at /workspace/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:478:22
    at onResponse (/workspace/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/teeny-request/build/src/index.js:226:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
```

**Comment by shaffeeullah** [comment]
Hi @meyerovb , 

Is `mybucketname` the actual name of the bucket that you're using with this function? If not, does your bucket name comply with the [bucket naming guidelines](https://cloud.google.com/storage/docs/naming-buckets)?

**Comment by shaffeeullah** [comment]
Closing due to inactivity. Please re-open if you're still seeing this issue.
