### ISSUE TITLE
System Test Failure?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#171]
*Originally reported by @JustinBeckwith*

Steps to reproduce:

- export GCLOUD_PROJECT={{projectId}}
- export GOOGLE_APPLICATION_CREDENTIALS={{pathToServiceAccountJSON}}
- npm run system-test

```
1) storage
       without authentication
         private data
           should not download a file:
     Uncaught TypeError: Cannot read property 'message' of null
      at /Users/beckwith/Code/nodejs-storage/system-test/storage.js:157:22
      at f (node_modules/once/once.js:25:25)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
      at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at endWritable (node_modules/readable-stream/lib/_stream_writable.js:628:3)
      at ConcatStream.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:584:41)
      at DestroyableTransform.onend (node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at endReadableNT (node_modules/readable-stream/lib/_stream_readable.js:1000:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
2) storage
       without authentication
         private data
           should not upload a file:
     Uncaught TypeError: Cannot read property 'message' of undefined
      at Pumpify.<anonymous> (system-test/storage.js:164:22)
      at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:482:3)
      at onwrite (node_modules/readable-stream/lib/_stream_writable.js:473:7)
      at Pumpify.WritableState.onwrite (node_modules/readable-stream/lib/_stream_writable.js:180:5)
      at Pumpify.Duplexify.uncork (node_modules/duplexify/index.js:74:50)
      at Duplexify.<anonymous> (src/file.js:1072:12)
      at Upload.<anonymous> (src/file.js:2348:11)
      at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:482:3)
      at onwrite (node_modules/readable-stream/lib/_stream_writable.js:473:7)
      at Upload.WritableState.onwrite (node_modules/readable-stream/lib/_stream_writable.js:180:5)
      at Upload.Duplexify.uncork (node_modules/duplexify/index.js:74:50)
      at Request.<anonymous> (node_modules/gcs-resumable-upload/index.js:174:12)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

@alexander-fenster @callmehiphop -- I can't reproduce, and it seems like Circle is fine, as well. Could you check and see how it works in your local environment?

**Comment by callmehiphop** [comment]
@stephenplusplus works fine for me (running Ubuntu 16.04)

**Comment by stephenplusplus** [comment]
Alright, let's just assume this was some weird hiccup. 👐
