### ISSUE TITLE
Could not resolve "../package.json" on v5.20.1

### ISSUE THREAD

**Issue by dryror** [googleapis/nodejs-storage#1934]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
library issue

2) Did someone already solve this?
Not that I can find

3) Do you have a support contract?
No

#### Environment details

  - OS: macOS
  - Node.js version: 14 and 16
  - npm version: 6.14.16 and 8.5.5
  - `@google-cloud/storage` version: v5.20.1

#### Steps to reproduce

  1. Install `@google-cloud/storage` and use it as a dependency in your project
  2. Package your project with esbuild
  3. See that it fails with the following errors:
```
✘ [ERROR] Could not resolve "../package.json"

    node_modules/@google-cloud/storage/build/src/storage.js:384:34:
      384 │             packageJson = require('../package.json');
          ╵                                   ~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../../package.json"

    node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:37:26:
      37 │     packageJson = require('../../package.json');
         ╵                           ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../package.json"

    node_modules/@google-cloud/storage/build/src/gcs-resumable-upload.js:37:26:
      37 │     packageJson = require('../package.json');
         ╵                           ~~~~~~~~~~~~~~~~~
```

I am using `firebase-admin` which has `@google-cloud/storage` as a dependency. When I pin `@google-cloud/storage` to `5.19.4` I can package my app fine with esbuild. When it is updated to `v5.20.1` it starts to fail with the above error.

**Comment by faradaytrs** [comment]
Same here

**Comment by timdp** [comment]
Also experiencing this.

Couldn't the complected fallthrough be avoided by having the same directory depth in both cases?

**Comment by ddelgrosso1** [comment]
Hello all, thank you for bringing this to our attention. I believe this should now be resolved in `5.20.2`. If you are still seeing issues please feel free to reopen.

**Comment by timdp** [comment]
As I [wrote](https://github.com/googleapis/nodejs-storage/pull/1936#issuecomment-1128910325) under #1936, I think that patch is neither necessary nor relevant.

**Comment by ddelgrosso1** [comment]
Thanks @timdp digging deeper into why this may be causing esbuild problems.

**Comment by faradaytrs** [comment]
Now there is problem in runtime 
 "Error: Unable to find package.json",
        "    at Object.getPackageJSON (/var/task/src/image.js:69669:13)",
        "    at node_modules/.pnpm/@google-cloud+storage@5.20.3/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js (/var/task/src/image.js:72893:30)",
        "    at __require (/var/task/src/image.js:40:50)",
        "    at node_modules/.pnpm/@google-cloud+storage@5.20.3/node_modules/@google-cloud/storage/build/src/nodejs-common/service.js (/var/task/src/image.js:73300:18)",
        "    at __require (/var/task/src/image.js:40:50)",
        "    at node_modules/.pnpm/@google-cloud+storage@5.20.3/node_modules/@google-cloud/storage/build/src/nodejs-common/index.js (/var/task/src/image.js:73700:21)",
        "    at __require (/var/task/src/image.js:40:50)",
        "    at node_modules/.pnpm/@google-cloud+storage@5.20.3/node_modules/@google-cloud/storage/build/src/bucket.js (/var/task/src/image.js:89418:27)",
        "    at __require (/var/task/src/image.js:40:50)",
        "    at node_modules/.pnpm/@google-cloud+storage@5.20.3/node_modules/@google-cloud/storage/build/src/index.js (/var/task/src/image.js:90189:20)"

**Comment by ddelgrosso1** [comment]
@faradaytrs I want to confirm that this is with an application built utilizing esbuild is that correct? If so, would you be able to provide what the configuration looks like?

**Comment by ddelgrosso1** [comment]
Just a quick update, I have been digging into the differences in `esbuild` output between `5.19.4` and `5.20.3`. Previously `esbuild` was able to inline the contents of `package.json` and wrap it in an internal function. When we made the pathing more "dynamic" in nature it appears `esbuild` is no longer able to do the same. While @timdp's suggestion may potentially fix this it would require some more build changes. We are currently looking at other possible alternatives.

**Comment by timdp** [comment]
I guess the alternative would be an esbuild patch that inclines `try { require(); ... }`. That seems pretty specific though and it's ultimately just working around (to my best knowledge) unnecessary complexity.

**Comment by ddelgrosso1** [comment]
After investigating the issue was the result of a change we made to support running unit tests directly in TypeScript. This caused us to move to dynamic requires for `package.json`. This caused `esbuild` to not be able to [analyze / inline](https://esbuild.github.io/api/#non-analyzable-imports) the `package.json` any more. We have reverted the change and gone back to a single require call that should again allow `esbuild` to inline the file. This will be released with `5.20.4`. I am going to leave this issue open in the meantime.

**Comment by ddelgrosso1** [comment]
Update: `5.20.4` has been published.

**Comment by timdp** [comment]
Seems fine again. Thanks!
