### ISSUE TITLE
`getSignedUrl()` is not working for fine-grained 

### ISSUE THREAD

**Issue by faizeev47** [googleapis/nodejs-storage#2001]
1) Is this a client library issue or a product issue?
Behaving like a client issue

2) Did someone already solve this?
  -https://github.com/googleapis/nodejs-storage/issues ➡️ NOT LOGGED
  -https://github.com/googleapis/google-cloud-node ➡️ NOT LOGGED
  -http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js ➡️ NO QUESTIONS

3) Do you have a support contract?

#### Environment details

  - OS: Windows 11
  - Node.js version: os➡️v18.4.0 , app engine➡️nodejs16
  - npm version: 8.12.1
  - `@google-cloud/storage` version: ^6.2.2

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/25141434/176973647-5bf79f5e-9460-4a56-84e4-af2f96222b06.png)

  1. Create File instance for bucket controlled by fine-grained ACL
  2. Get signed URL for file

#### Error
![image](https://user-images.githubusercontent.com/25141434/176973360-59cf3b9c-860f-4ff2-ad7b-857539a784b1.png)
```
022-07-01 21:25:33 ptaas-website[20220702t020825]  node:internal/process/promises:279
2022-07-01 21:25:33 ptaas-website[20220702t020825]              triggerUncaughtException(err, true /* fromPromise */);
2022-07-01 21:25:33 ptaas-website[20220702t020825]              ^
2022-07-01 21:25:33 ptaas-website[20220702t020825]
2022-07-01 21:25:33 ptaas-website[20220702t020825]  Error: The caller does not have permission      at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:130:23)      at processTicksAndRejections (node:internal/process/task_queues:96:5)      at async Compute.requestAsync (/workspace/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)      at async GoogleAuth.signBlob (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:655:21)      at async sign (/workspace/node_modules/@google-cloud/storage/build/src/signer.js:103:35) {
2022-07-01 21:25:33 ptaas-website[20220702t020825]    name: 'SigningError'
2022-07-01 21:25:33 ptaas-website[20220702t020825]  }
```

#### Call
``` javascript
exports.GCSCheckRoute = async function(req, res) {
  console.log("hello");
  const storage = new Storage();
  const myBucket = storage.bucket("ptsm-bucket");

  var actionIndex = "0";
  let scriptName = "Chat_Script.xml";
  if (actionIndex == "0") {
    scriptName = "Call_Script.xml";
  }
  else if (actionIndex == "1") {
    scriptName = "Chat_Script.xml";
  }
  else if (actionIndex == "2") {
    scriptName = "Digital_Script.xml";
  }
  const file = myBucket.file(`scripts/${scriptName}`)

  file.setUserProject("devops-sandbox-353314");

  var url = await file.getSignedUrl({
    action: 'read',
    expires: new Date().setDate(new Date().getDate() + 1),
  });
  return res.json({url: url});
}
```

**Comment by ddelgrosso1** [comment]
Hi @faizeev47 thank you for the question. From the looks of the error you are getting it appears to me that the service account you are using to sign the url does not have the correct permissions. Have you verified that the service account has the IAM permission `iam.serviceAccounts.signBlob` and `iam.serviceAccountTokenCreator`?

**Comment by ddelgrosso1** [comment]
I am going to close this issue due to inactivity. If there is more information available please feel free to reopen.
