### ISSUE TITLE
`Invalid Credentials` error trying to get signed url

### ISSUE THREAD

**Issue by igor47** [googleapis/nodejs-storage#2115]
#### Environment details

  - OS: linux
  - Node.js version: 18.12.1
  - npm version: 8.19.2
  - `@google-cloud/storage` version: 6.8.0

I am using google-cloud-storage with a service account key. A code path like this:

```
import { GoogleAuth } from 'google-auth-library'
import { Storage } from '@google-cloud/storage'

const authClient = new GoogleAuth({
  keyFile: './keyfile.json',
 })
const client = new Storage({ authClient })
const bucket = client.bucket('my-bucket')
const file = bucket.file('my-file')
file.save('some contents')

return file.getSignedUrl({
  version: 'v4',
  action: 'read',
  expires: new Date(new Date().valueOf() + 1000 * 60 * 15),
})
```

results in an error like this:
```

Error: Unknown error.
    at GoogleAuth.getCredentialsAsync (/home/igor47/repos/myproject/node_modules/@google-cloud/storage/node_modules/google-auth-library/build/src/auth/googleauth.js:608:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sign (/home/igor47/repos/myproject/node_modules/@google-cloud/storage/build/src/signer.js:156:33)
listing files...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ApiError: Invalid Credentials
    at new ApiError (/home/igor47/repos/myproject/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:79:15)
    at Util.parseHttpRespBody (/home/igor47/repos/myproject/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:214:38)
    at Util.handleResp (/home/igor47/repos/myproject/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:155:117)
    at /home/igor47/repos/myproject/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:536:22
    at onResponse (/home/igor47/repos/myproject/node_modules/retry-request/index.js:240:7)
    at <anonymous> (/home/igor47/repos/myproject/node_modules/teeny-request/src/index.ts:333:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 401,
  errors: [
    {
      message: 'Invalid Credentials',
      domain: 'global',
      reason: 'authError',
      locationType: 'header',
      location: 'Authorization'
    }
  ],
  response: PassThrough {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [ [Function (anonymous)], [Function (anonymous)] ],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: true,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    statusCode: 401,
    statusMessage: 'Unauthorized',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          maxSockets: Infinity,
          keepAlive: true,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {
          'storage.googleapis.com:443:::::::::::::::::::::': [ [TLSSocket] ]
        },
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'storage.googleapis.com:443:::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'storage.googleapis.com:443:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      headers: {
        'User-Agent': 'gcloud-node-storage/6.8.0',
        'x-goog-api-client': 'gl-node/18.12.1 gccl/6.8.0 gccl-invocation-id/d3e3e0cb-cf40-4ebb-88ca-89a55bc8c2c4',
        Authorization: 'Bearer token-was-here'
      },
      href: 'https://storage.googleapis.com/storage/v1/b/myproject-app/o?'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 401,\n' +
      '    "message": "Invalid Credentials",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Invalid Credentials",\n' +
      '        "domain": "global",\n' +
      '        "reason": "authError",\n' +
      '        "locationType": "header",\n' +
      '        "location": "Authorization"\n' +
      '      }\n' +
      '    ]\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      'content-length': '285',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Fri, 09 Dec 2022 00:53:07 GMT',
      expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
      pragma: 'no-cache',
      server: 'UploadServer',
      vary: 'Origin, X-Origin',
      'www-authenticate': 'Bearer realm="https://accounts.google.com/"',
      'x-guploader-uploadid': 'ADPycdsRdJdYHJ3AFaW5V7MhiFEw4OB6awjhDBRwXSp-n8KpNEDLQ-Mj7nGXUbjjA3AuaYCpBoeH1Zpe_l95vfvVdn2m'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  }
}

Node.js v18.12.1
error Command failed.
Exit code: 1
```

the file is created, so my credential is not TOO invalid. not sure what to do next here.

**Comment by igor47** [comment]
this is basically almost the exact example used in the documentation:
https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#code-samples

the docs don't show how to use a service account credential, but given that other types of requests (like writing to a file) work, i'm not really sure why specifically only signing urls fails.

**Comment by igor47** [comment]
here's a complete script to reproduce the issue; all you need is a service account keyfile. for the record, using the exact same keyfile with `gsutil` like so:

```shell
$ gsutil signurl -d 15m -r asia-east-1 ./service-account.json  gs://mybucket/testfile
```

works just fine and produces a working url, so i'm pretty sure the problem is somewhere in the bowels of the nodejs tooling here.

```nodejs
import { Storage } from '@google-cloud/storage'
import { GoogleAuth } from 'google-auth-library'

// The ID of your GCS bucket
const bucketName = 'mybucket'

// The full path of your file inside the GCS bucket, e.g. 'yourFile.jpg' or 'folder1/folder2/yourFile.jpg'
const fileName = 'testfile'

// Creates a client
const storage = new Storage({
  authClient: new GoogleAuth({
    keyFile: '/home/igor47/service-account.json',
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  }),
})

async function generateV4ReadSignedUrl() {
  // These options will allow temporary read access to the file
  const options = {
    version: 'v4',
    action: 'read',
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
  } as const;

  // Get a v4 signed URL for reading the file
  const [url] = await storage
    .bucket(bucketName)
    .file(fileName)
    .getSignedUrl(options);

  console.log('Generated GET signed URL:');
  console.log(url);
  console.log('You can use this URL with any user agent, for example:');
  console.log(`curl '${url}'`);
}

generateV4ReadSignedUrl().catch(console.dir);
```

**Comment by igor47** [comment]
i did a little more digging on this, and it has to do with how i was passing auth. the following code is broken, producing the error i described:

```node
const authClient = new GoogleAuth({
  credentials: json_key_body,
 })
const client = new Storage({ authClient })
```

while the following code works:
```node
    const client = new Storage({
      credentials: json_key_body,
    })
```

i would expect those two code paths to be equivalent, and they mostly are, except for (AFAICT) the signed url path. maybe has something to do with how the google auth client is instantiated or used inside the storage client?

**Comment by unterstein** [comment]
@danielbankhead while this issue can be worked around by the example by @igor47, it is still broke for passing in a `GoogleAuth` to `Storage`.

We are facing the exact same behaviour and unfortunately we can't just pass in the `credentials` property directly to `Storage`, we are bound to pass in the `GoogleAuth` object to `Storage`.

We are using this in combination with a `OAuth2Client` as `authClient` for `GoogleAuth`.

**Comment by TheXienator** [comment]
Hi @danielbankhead, I was wondering if there are any plans to make the authClient you pass into Storage work with an instance of the Impersonated class?

I was hoping to do something like this for local development testing:

```
        // Acquire source credentials:
        const auth = new GoogleAuth()
        const client = await auth.getClient()

        new ExternalAccountClient()
        // Impersonate new credentials:
        const targetClient = new Impersonated({
            sourceClient: client,
            targetPrincipal: "<service_email>",
            lifetime: 30,
            targetScopes: [
                "https://www.googleapis.com/auth/devstorage.read_only",
            ],
        })

        const storageParams: StorageOptions = {
            projectId: cloudProject,
            authClient: targetClient,
        }
        const storage = new Storage(storageParams)
```

But it seems to fail at getCredentialsAsync here: https://github.com/googleapis/google-auth-library-nodejs/blob/fb40dd7be53dbeb34a10521050fb14e4cc44e6e9/src/auth/googleauth.ts#L850-L868

It is because Impersonated is an instance of OAuth2Client and not of BaseExternalAccountClient and I don't have a `this.jsonContent` because I wanted to Impersonate my service account instead of having the credentials have to be downloaded locally.

And lastly the `isGCE` check fails because I am running this on my local machine so I get the same `Unknown error.'` that igor47 got, but I am not able to resolve it how he resolved it because I do not want to expose my `json_key` locally.

**Comment by danielbankhead** [comment]
@TheXienator thanks for this information - Storage currently supports any `AuthClient`, so it should work. The problem you're describing is purely within the auth library - do you mind filing an issue there?

**Comment by TheXienator** [comment]
Hi @danielbankhead I think I actually found an existing issue in the auth library that describes my problem better here: https://github.com/googleapis/google-auth-library-nodejs/issues/1443

**Comment by danielbankhead** [comment]
@TheXienator sounds good - I'll have some time in the coming weeks to work on that library's backlog
