### ISSUE TITLE
support esm

### ISSUE THREAD

**Issue by eng-dibo** [googleapis/nodejs-storage#2117]
when importing `@google-cloud/storage` from an esm project this error occurs:
```
 Must use import to load ES Module: node_modules\abort-controller\dist\abort-controller.mjs

    > 1 | import {  Bucket, DownloadResponse, File, SaveOptions, Storage, UploadResponse, StorageOptions } from '@google-cloud/storage'
        | ^
   

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:817:21)
      at Object.<anonymous> (node_modules/@google-cloud/storage/build/src/gcs-resumable-upload.js:17:28)
      at Object.<anonymous> (node_modules/@google-cloud/storage/build/src/file.js:29:25)
      at Object.<anonymous> (node_modules/@google-cloud/storage/build/src/bucket.js:30:16)
      at Object.<anonymous> (node_modules/@google-cloud/storage/build/src/index.js:16:16)
      at Object.<anonymous> (packages/gcloud-storage/index.ts:1:1)
      at Object.<anonymous> (packages/gcloud-storage/index.spec.ts:2:1)
```

[minimal reproduction](https://github.com/eng-dibo/issue-gcloud-esm)
run `npm t`

**Comment by eng-dibo** [comment]
fixed by https://github.com/kulshekhar/ts-jest/issues/3929#issuecomment-1345582824
