### ISSUE TITLE
TypeError: readable is not async iterable on file download

### ISSUE THREAD

**Issue by daniel-odc** [googleapis/nodejs-storage#2128]
Hi
I am trying to read data from a Google Cloud Storage bucket from a React application.
My bucket cannot be public to the internet. I have created a service account to give my app the authorization to access the bucket.
I can access the bucket and list the files but cannot download the content of the file: I get the following error:
**TypeError: readable is not async iterable**

I created my app with create-react-app and my node module versions are:
`"react": "^18.2.0",`
`"@google-cloud/storage": "^6.8.0",`

My code is as follows:

```
import React, {useState} from 'react';
import {Storage} from "@google-cloud/storage";
import jsonKey from '../keys/`[my-json-key].json';


export default function TestsLight() {

    const [fileData, setFileData] = useState(null);

    /*  Files and Bucket details: */
    const file_name = 'my-file.csv';
    const bucketName = 'my-bucket.appspot.com';

    /*  Storage instantiation: works:   */
    const storage = new Storage({credentials: jsonKey});
    const bucket = storage.bucket(bucketName);
    const myFile = bucket.file(file_name);

    /*  file download: DOES NOT WORK: returns `TypeError: readable is not async iterable`   */
    myFile.download(function (err, contents) {
        console.log('err: ', err);
        console.log('contents: ', contents);
        contents && setFileData(contents);
    });

    return (
        fileData ?
            <div>
                {fileData}
            </div> :
            <div>
                <span>no data</span>
            </div>
    )
}

```

I followed the steps from 

https://cloud.google.com/nodejs/docs/reference/storage/latest

I tried to:
- create a bucket: *works*
- list the files in a bucket: *works*
- download the content of the file in memory or in a local file: *does not work*: **TypeError: readable is not async iterable**

Any idea of what is wrong?
Many thanks

**Comment by ddelgrosso1** [comment]
Hi @daniel-odc thank you for the question. Currently the NodeJS Storage library does not support being run in a browser. The error you are seeing is likely caused by the fact that the library makes use of many core Node libraries that would need to be polyfilled in the browser. While it may be possible to create a Webpack / Rollup / etc... configuration that gets things working, it isn't something we have done a lot of testing with and so I couldn't offer much guidance in that area.

However, if you are trying to download a file one alternative is to [generate a signed url ](https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers) on the server side, pass this URL to the client side, and use the HTTP library of your choice to download the file that way. Let me know if you have any other questions.

**Comment by daniel-odc** [comment]
Hi @ddelgrosso1 
many thanks for your time and answer. 
I tried your solution, updating my code as following your link, but still get an error:
**TypeError: url.URL is not a constructor**

```
/*  Test creating a signed URL: */
    async function generateV4ReadSignedUrl() {
        /* These options will allow temporary read access to the file   */
        const options = {
            version: 'v4',
            action: 'read',
            expires: Date.now() + 15 * 60 * 1000, // 15 minutes
        };

        /* Get a v4 signed URL for reading the file   */
        const [url] = await storage
            .bucket(bucketName)
            .file(fileName)
            .getSignedUrl(options);

        console.log(url);        
    }

    generateV4ReadSignedUrl().catch(console.error);
```
Is there anything I missed here?
Many thanks

**Comment by ddelgrosso1** [comment]
Hi @daniel-odc just to clarify, the code you supplied in your most recent comment is being executed on the server side? If so, what version of Node are you utilizing?

**Comment by daniel-odc** [comment]
Hi Denis
my code is executed through Pycharm IDE using node.exe version `14.14.2`, npm version `8.5.0`
many thanks

**Comment by ddelgrosso1** [comment]
You wouldn't happen to have a stack trace available by chance? Feel free to remove anything that might be sensitive / confidential to your application.

**Comment by daniel-odc** [comment]
sure, here is the full error message:
(the full code being the first bloc above, with the `download` block replaced by the second `/*  Test creating a signed URL: */` block)

```
TypeError: url.URL is not a constructor
    at URLSigner.getSignedUrlV4 (signer.js:131:1)
    at URLSigner.getSignedUrl (signer.js:76:1)
    at File.getSignedUrl (file.js:2269:1)
    at index.js:57:1
    at new Promise (<anonymous>)
    at File.wrapper (index.js:42:1)
    at generateV4ReadSignedUrl (TestsLight.js:45:1)
    at TestsLight (TestsLight.js:56:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
    at onGlobalMessage (setImmediate.js:109:1)
```

**Comment by ddelgrosso1** [comment]
Please correct me if I am reading something incorrectly. From the looks of the stack trace you provided it appears that the code is still being executed within a React context (and thus I am assuming in the browser). To clarify my earlier comments a signed URL would need to be generated from a Node API / server context completely separate from the React side of things.

**Comment by daniel-odc** [comment]
Hi Denis
thanks again for your time.
Let me be more clear: I am developping my React app locally before deploying it to App Engine. To do so, I use Pycharm that emulates the server. It runs smoothly, no error message on the server side. Here is the log console on the server side:

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto
> 04_odc_dashboard@0.1.0 start
> react-scripts start
i ｢wds｣: Project is running at http://172.27.192.1/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\[my-app-files-local-path]\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
Compiled with warnings.

./node_modules/retry-request/index.js
Module not found: Can't resolve 'request' in 'C:\Users\[my-app-files-local-path]\node_modules\retry-request'


// some warnings

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

The error appears in the browser console indeed.
If you say that the signed URL needs to be generated from a Node API / server context, what are the options then to be able to read (or upload) a file from a React application then?
And how come other examples from https://cloud.google.com/nodejs/docs/reference/storage/latest do work (eg create a bucket or list the files from the bucket)?
Many thanks

**Comment by ddelgrosso1** [comment]
Thanks for the additional information. While I haven't done much work with React, I have with Vue and from your most recent update it looks like a similar set of scripts available for React. I believe that these scripts build the application utilizing Webpack and start a development web server that serves up the application. Your code would still be running inside the browser. As I mentioned, I would not expect the storage library to work under these conditions.

When I am referencing a Node API server, I am referring to something like a Node/Express application. This would need to be separated from the web server / web code. A quick search [turned up this old guide](https://medium.com/free-code-camp/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0) on doing this with `create-react-app`. From this Node / Express application you could create an endpoint that the web application calls. This endpoint would invoke the appropriate signed url function and return the created URL to the web application. This URL can then be used with the HTTP library of your choice to upload the file, no storage library needed within the frontend application.

To the second part of your question on why some operations succeed in the browser. Some library functions are pretty simple under the hood and basically just make a HTTP call. When you start to get into things like uploading and downloading it becomes a bit more complex and we utilize a greater number of Node libraries, for example, streams.

We get questions regarding using the storage library in the browser pretty regularly and it is something that we are discussing internally. However, there is no timeline currently for when / if we will support this.

**Comment by daniel-odc** [comment]
Hi Denis
ok, many thanks for spending time on this.
I think I am just going to create a dedicate API in charge of loading the files, and then access the files content through calls from my app to this API.
Have a great week
