### ISSUE TITLE
"Could not load the default credentials" when using custom apiEndpoint with getSignedUrl.

### ISSUE THREAD

**Issue by psigen** [googleapis/nodejs-storage#2197]
#### Environment details

  - OS: Ubuntu 22.04
  - Node.js version: v18.15.0
  - npm version: 9.5.0
  - `@google-cloud/storage` version: 6.10.0

#### Steps to reproduce

Run the following code using a storage emulator host setting in the environment:
```
STORAGE_EMULATOR_HOST=http://localhost:9199/
```

```
import { Storage } from "@google-cloud/storage";

const storage = new Storage({
  useAuthWithCustomEndpoint: false,
});

const expiration = new Date();
const expirationSecs = 60 * 10; // 10 minutes
expiration.setSeconds(expirationSecs);

const options = {
  version: "v4" as const,
  action: "read" as const,
  expires: expiration,
};

const [url] = await storage.bucket(BUCKET_NAME)
  .file(path)
  .getSignedUrl(options);
```

This will return the following error about credentials, even though the emulator doesn't use credentials, so they aren't needed to sign the URL:
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/app/api/index.js:65733:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth.getClient (/app/api/index.js:66050:20)
    at async GoogleAuth.getCredentialsAsync (/app/api/index.js:66009:24)
    at async sign (/app/api/index.js:93784:33)
```

This was previously mentioned in a comment on this previous ticket: https://github.com/googleapis/nodejs-storage/issues/1373#issuecomment-1140351554

**Comment by ddelgrosso1** [comment]
@danielbankhead I poked into this a bit and it appears that the problem comes in that there doesn't be a way to tell the auth library to "faux" sign a request. Is there a clean way we can bypass this in storage when the user does not want to use authentication?

**Comment by danielbankhead** [comment]
[discussed offline, sharing here] We may need to take a similar approach as https://github.com/googleapis/gcs-resumable-upload/pull/416 for this issue.

**Comment by BrennaEpp** [comment]
Hijacking this issue to track the implementation of this feature:

When a custom endpoint is set on the client, Sign URLs and Post Policies should automatically use that domain.

Optional: allow users to set a custom hostname for Sign URL and Post policy methods

See: go/signurl-custom-endpoint-gcs

**Comment by danielbankhead** [comment]
Related:
- https://github.com/googleapis/nodejs-storage/issues/2092
