### ISSUE TITLE
Not Found error is too generic for a non-existant bucket

### ISSUE THREAD

**Issue by gauntface** [googleapis/nodejs-storage#220]
I just tried to use a bucket that doesn't exist (not understanding that I had to manually check for existance and create).

The error I got was really too generic to be developer friendly.

The errror I got was:

```
{ ApiError: Not Found
crawler_1    |     at Object.parseHttpRespBody (/opt/ghcrawler/node_modules/@google-cloud/common/src/util.js:193:30)
crawler_1    |     at Object.handleResp (/opt/ghcrawler/node_modules/@google-cloud/common/src/util.js:131:18)
crawler_1    |     at /opt/ghcrawler/node_modules/@google-cloud/common/src/util.js:496:12
crawler_1    |     at Request.onResponse [as _callback] (/opt/ghcrawler/node_modules/retry-request/index.js:195:7)
crawler_1    |     at Request.self.callback (/opt/ghcrawler/node_modules/request/request.js:185:22)
crawler_1    |     at emitTwo (events.js:106:13)
crawler_1    |     at Request.emit (events.js:191:7)
crawler_1    |     at Request.<anonymous> (/opt/ghcrawler/node_modules/request/request.js:1157:10)
crawler_1    |     at emitOne (events.js:96:13)
crawler_1    |     at Request.emit (events.js:188:7)
crawler_1    |     at IncomingMessage.<anonymous> (/opt/ghcrawler/node_modules/request/request.js:1079:12)
crawler_1    |     at IncomingMessage.g (events.js:292:16)
crawler_1    |     at emitNone (events.js:91:20)
crawler_1    |     at IncomingMessage.emit (events.js:185:7)
crawler_1    |     at endReadableNT (_stream_readable.js:974:12)
crawler_1    |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
crawler_1    |   code: 404,
crawler_1    |   errors:
crawler_1    |    [ { domain: 'global',
crawler_1    |        reason: 'notFound',
crawler_1    |        message: 'Not Found',
crawler_1    |        debugInfo: 'com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::BUCKET_NOT_FOUND: c: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:118)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:131)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:61)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:174)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:39)\n\tat com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:293)\n\tat com.google.cloud.bigstore.api.json.ObjectsDelegator.list(ObjectsDelegator.java:89)\n\tat com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$3(RpcReceiver.java:166)\n\tat com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:243)\n\tat com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:276)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:122)\n\t... 18 more\n\ncom.google.api.server.core.Fault: ImmutableErrorDefinition{base=NOT_FOUND, category=USER_ERROR, cause=null, debugInfo=com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::BUCKET_NOT_FOUND: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:118)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:131)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:61)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:174)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:39)\n\tat com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:293)\n\tat com.google.cloud.bigstore.api.json.ObjectsDelegator.list(ObjectsDelegator.java:89)\n\tat com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$3(RpcReceiver.java:166)\n\tat com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:243)\n\tat com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException: BUCKET_NOT_FOUND: No suchbucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:276)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:122)\n\t... 18 more\n, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=notFound, internalReason=Reason{arguments={}, cause=null, code=gdata.CoreErrorDomain.NOT_FOUND, createdByBackend=true, debugMessage=com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::BUCKET_NOT_FOUND: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:118)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:131)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:61)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:174)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:39)\n\tat com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:293)\n\tat com.google.cloud.bigstore.api.json.ObjectsDelegator.list(ObjectsDelegator.java:89)\n\tat com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$3(RpcReceiver.java:166)\n\tat com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:243)\n\tat com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:276)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:122)\n\t... 18 more\n, errorProtoCode=NOT_FOUND, errorProtoDomain=gdata.CoreErrorDomain, filteredMessage=null, location=entity.bucket, message=null, unnamedArguments=[]}, location=entity.bucket, message=Not Found, reason=notFound, rpcCode=404} Not Found: com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::BUCKET_NOT_FOUND: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:118)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:131)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:61)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:174)\n\tat com.google.cloud.bigstore.api.json.handlers.objects.ListObjects.handleRequestReceived(ListObjects.java:39)\n\tat com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:293)\n\tat com.google.cloud.bigstore.api.json.ObjectsDelegator.list(ObjectsDelegator.java:89)\n\tat com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$3(RpcReceiver.java:166)\n\tat com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:243)\n\tat com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException: BUCKET_NOT_FOUND: No such bucket: ghcrawler-deadletter\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:276)\n\tat com.google.cloud.bigstore.api.json.framework.BackendCallUtil.call(BackendCallUtil.java:122)\n\t... 18 more\n\n\tat com.google.api.server.core.ErrorCollector.toFault(ErrorCollector.java:54)\n\tat com.google.api.server.rest.adapter.rosy.RosyErrorConverter.toFault(RosyErrorConverter.java:67)\n\tat com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:258)\n\tat com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:238)\n\tat com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:402)\n\tat com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)\n\tat com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)\n\tat com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:694)\n\tat com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:402)\n\tat com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)\n\tat com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)\n\tat com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:694)\n\tat com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat com.google.api.server.thread.ThreadTrackers$ThreadTrackingRunnable.run(ThreadTrackers.java:126)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)\n\tat com.google.api.server.server.CommonModule$ContextCarryingExecutorService$1.runInContext(CommonModule.java:839)\n\tat com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)\n\tat com.google.gse.internal.DispatchQueueImpl$WorkerThread.run(DispatchQueueImpl.java:403)\n' } ],
crawler_1    |   response: undefined,
crawler_1    |   message: 'Not Found' }
```

If `Not Found` was change to `Bucket does not exist`, it would be much easier to follow and diagnose the problem.

**Comment by fhinkel** [comment]
@stephenplusplus Can we assign this to you?

**Comment by stephenplusplus** [comment]
@gauntface can you show the code you used that returned this error?

**Comment by gauntface** [comment]
I don't but I think it's something along the lines of:

```
const bucket = storage.bucket("does-not-exit");
const file = this.bucket.file("filename");
await file.save("hello,world");
```

Basically - use the bucket before it exists.

**Comment by AVaksman** [comment]
@gauntface It seems like there is not many options to fix this from the client library side. We need a more informational error message from the server stating the resource name/type that is `"Not Found"` (a `bucket`, a `file`). I would kindly refer you [here](https://cloud.google.com/storage/docs/getting-support#file_bugs_or_feature_requests) to report an issue or request a feature on the server side.
