### ISSUE TITLE
`getSignedUrl()` have a something bag.

### ISSUE THREAD

**Issue by ogawa0071** [googleapis/nodejs-storage#296]
#### Environment details

  - OS: macOS 10.13.6 / Google App Engine Standard Environment
  - Node.js version: 10.5.0 / 8.x.x
  - npm version: 6.1.0 / x.x.x
  - `@google-cloud/storage` version: 1.7.0

---

Look test code running on the **Google App Engine Standard Environment for Node.js**.

Premise: 
- Useing IAM: **App Engine default service account / App Engine's Application Default Credentials (ADC)**
- Running script: **`GCLOUD_STORAGE_BUCKET=YOUR_GCLOUD_STORAGE_BUCKET node test.js`**

I changed settings before running: 
- **I turned on `Identity and Access Management (IAM) API`.**
- **I added IAM role `roles/iam.serviceAccountTokenCreator` to App Engine default service account (PROJECT_ID@appspot.gserviceaccount.com).**

```test.js
const Storage = require("@google-cloud/storage");
const express = require("express");

const GCLOUD_STORAGE_BUCKET = (() => {
  if (!process.env.GCLOUD_STORAGE_BUCKET) {
    throw new Error();
  }

  return process.env.GCLOUD_STORAGE_BUCKET;
})();
const storage = Storage();
const bucket = storage.bucket(GCLOUD_STORAGE_BUCKET);


const app = express();

app.get("/test", async (req, res) => {
  const signedUrls = await get();

  res.json(signedUrls);
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`listening on ${port}`);
});


const get = async () => {
  const files = await bucket.getFiles().catch(err => {
    throw err;
  });

  if (!files[0][0]) {
    throw new Error();
  }

  const signedUrls = await files[0][0].getSignedUrl();

  return signedUrls;
};
```

It returned 500 error and this logs.

```
/srv/node_modules/@google-cloud/storage/src/file.js:1818
    callback(null, signedUrl);
    ^

TypeError: callback is not a function
    at /srv/node_modules/@google-cloud/storage/src/file.js:1818:5
    at Request._callback (/srv/node_modules/google-auto-auth/index.js:362:9)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
```

# Without using this client and use `google-auth-library`

At first, I thought it was an error caused by IAM setting, but it is not wrong.

**I tried create signed url without using this client, and using [`google-auth-library`](https://github.com/google/google-auth-library-nodejs).**

Reference documents: 
https://cloud.google.com/storage/docs/access-control/create-signed-urls-program
https://cloud.google.com/storage/docs/access-control/signed-urls

```test.js
const Storage = require("@google-cloud/storage");
const { auth } = require("google-auth-library");
const express = require("express");

const GCLOUD_STORAGE_BUCKET = (() => {
  if (!process.env.GCLOUD_STORAGE_BUCKET) {
    throw new Error();
  }

  return process.env.GCLOUD_STORAGE_BUCKET;
})();
const storage = Storage();
const bucket = storage.bucket(GCLOUD_STORAGE_BUCKET);

const app = express();

app.get("/test", async (req, res) => {
  const signedUrls = await get();

  res.json(signedUrls);
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`listening on ${port}`);
});

const get = async () => {
  const files = await bucket.getFiles().catch(err => {
    throw err;
  });

  if (!files[0][0]) {
    throw new Error();
  }

  // const signedUrls = await files[0][0].getSignedUrl();
  const signedUrls = await getSignedUrl(files[0][0]);

  return signedUrls;
};

const getSignedUrl = async file => {
  const metadata = (() => {
    if (!file.metadata) {
      throw new Error();
    }

    return file.metadata;
  })();

  const settings = {
    HTTP_Verb: "GET",
    Content_MD5: "",
    Content_Type: "",
    Expiration: Date.now() + 3600,
    Canonicalized_Extension_Headers: "",
    Canonicalized_Resource: `/${metadata.bucket}/${metadata.name}`
  };

  const signature_sign =
    settings.HTTP_Verb +
    "\n" +
    settings.Content_MD5 +
    "\n" +
    settings.Content_Type +
    "\n" +
    settings.Expiration +
    "\n" +
    // settings.Canonicalized_Extension_Headers +
    // "\n" +
    settings.Canonicalized_Resource;

  const signature_signed = encodeURIComponent(await auth.sign(signature_sign));

  const BASE_URL =
    "https://storage.googleapis.com" + settings.Canonicalized_Resource;
  const GOOGLE_ACCESS_STORAGE_ID = (await auth.getCredentials()).client_email;
  const URL_ENCODED_SIGNATURE = signature_signed;

  const signedUrl =
    BASE_URL +
    "?GoogleAccessId=" +
    GOOGLE_ACCESS_STORAGE_ID +
    "&Expires=" +
    settings.Expiration +
    "&Signature=" +
    URL_ENCODED_SIGNATURE;

  return signedUrl;
};
```

It returned 200 and correct response!

So, I concluded that this library's `getSignedUrl()` method have a bug.

**Comment by ogawa0071** [comment]
I got a revelation!!!
My issue is wrong...

But, this client's `getSignedUrl()` error message is not good.
So, I am closing it and I will create new issue.

**Comment by ogawa0071** [comment]
Create new issue: 
https://github.com/googleapis/nodejs-storage/issues/301
