### ISSUE TITLE
`getSignedUrl()`'s error message is not good.

### ISSUE THREAD

**Issue by ogawa0071** [googleapis/nodejs-storage#301]
#### Environment details

- OS: macOS 10.13.6 / Google App Engine Standard Environment
- Node.js version: 10.5.0 / 8.x.x
- npm version: 6.1.0 / x.x.x
- `@google-cloud/storage` version: 1.7.0

#### Steps to reproduce

`getSignedUrl()` is need options like this.

```javascript
const getSignedUrl = async file => {
  const signedUrl = await file.getSignedUrl({
    action: "read",
    expires: Date.now() + 3600000
  });

  return signedUrl;
};
```

If you don't set options like this, return error message.

```javascript
const getSignedUrl = async file => {
  const signedUrl = await file.getSignedUrl();

  return signedUrl;
};
```

```logs
/srv/node_modules/@google-cloud/storage/src/file.js:1818
    callback(null, signedUrl);
    ^

TypeError: callback is not a function
    at /srv/node_modules/@google-cloud/storage/src/file.js:1818:5
    at Request._callback (/srv/node_modules/google-auto-auth/index.js:362:9)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
```

**So I think that this client should return error message like `getSignedUrl() need options (action, expires).`**

**Comment by stephenplusplus** [comment]
Thanks for the suggestion, and sorry this tripped you up. If you're interested, a PR that does something like...

```js
if (!config) {
  throw new Error('A configuration object is required.');
}
```

...would be great!

**Comment by ogawa0071** [comment]
@stephenplusplus OK, I will create PR👍

**Comment by stephenplusplus** [comment]
Nice, thanks!
