### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ils-sapnaj** [googleapis/nodejs-storage#466]
node 8.11.4
npm 5.6.0
@google-cloud/storage 2.0.3

Here is my code -

```js
Object.prototype.fileUpload = function(fileName, file_path, req, callback){
	var fs = require("fs");
	var mime = require('mime-types')
	var mimetyp = mime.lookup(file_path);
	var constants = req.app.get('constants');
	var project_id = constants.GCP_PROJECT_ID;
	var CLOUD_BUCKET = constants.GCP_BUCKET_NAME;
	var space = constants.APP_ENVIRONMENT;
	var bucketPath = space + '/'+'xxx@gmail.com'+'/'+fileName;
	var GCP_access_url = constants.GCP_ACCESS_URL;
	var googleStorage = req.app.get('googleStorage');

	const storage = new googleStorage({
        projectId: project_id,
        keyFilename: './GCP_credential.json'
        // or...
        //credentials: require('./GCP_credential.json')
      
	})
    
    var bucket = storage.bucket(CLOUD_BUCKET);
    
    var files = bucket.file(bucketPath);

    fs.createReadStream(file_path)
    .pipe(files.createWriteStream
    ({
      	metadata:
      	{
        	contentType: mimetyp
      	},
      	predefinedAcl: "publicRead"
    }))
    .on("error", (err) =>
    {
      	console.log("err : "+err);
      	callback(err);
    })
    .on('finish', () =>
    {
      	callback(null, 'Success');
    });
} 
```

I have required google cloud storage package in app.js. I am getting following error when trying to call the above function : 

```
TypeError: Cannot read property '0' of undefined
    at Mime.define (D:\XXX\node_modules\gtoken\node_modules\mime\Mime.js:43:14)
    at new Mime (D:\XXX\node_modules\gtoken\node_modules\mime\Mime.js:12:10)
    at Object.<anonymous> (D:\XXX\node_modules\gtoken\node_modules\mime\index.js:4:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by ils-sapnaj** [comment]
Hey, I have debugged it further and found the place from where I am getting this error - file:///D:/XXX/node_modules/mysql/lib/protocol/Parser.js at line no 87.

I have seen this behavior at other places also where adding the sql queries causing the issue. Seems strange but is there any connection related to Mysql or communication with mysql due to which I am getting weird errors.

In my code structure, I have a communication with mysql as well as google cloud bucket.

Also I am seeing same error in my unit test of google bucket upload.

**Comment by stephenplusplus** [comment]
@ils-sapnaj would you be able to put together a reproduction repo, that we can clone, install, and run to see the error? Ideally, stripping the application to only our library would help minimize the risk of unrelated failures. Thanks!
