### ISSUE TITLE
Samples test errors

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-storage#53]
From master:

```
$ cd samples
$ npm run test

> @google-cloud/storage-samples@0.0.1 test C:\Users\sawch\dev\nodejs-storage\samples
> repo-tools test run --cmd npm -- run cover

run: Executing tests in: C:\Users\sawch\dev\nodejs-storage\samples
run: Running: npm run cover

> @google-cloud/storage-samples@0.0.1 cover C:\Users\sawch\dev\nodejs-storage\samples
> nyc --reporter=lcov --cache ava -T 20s --verbose system-test/*.test.js && nyc report


  √ quickstart » should create a bucket (1s)
  - requesterPays » should error on requester-pays requests if they are disabled
  √ encryption » should generate a key (431ms)
  √ buckets » should create a bucket (1.9s)
  √ requesterPays » should fetch requester-pays status on a default bucket (1.1s)
  √ iam » should add multiple members to a role on a bucket (1.6s)
  × files » should upload a file
  × encryption » should upload a file
  √ buckets » should list buckets (1.1s)
  √ requesterPays » should enable requester-pays requests (1.3s)
  √ acl » should print a user's acl for a bucket (2.4s)
  √ iam » should list members of a role on a bucket (1.1s)
  × files » should download a file
  × encryption » should download a file
  √ buckets » should delete a bucket (1.2s)
C:\Users\sawch\dev\nodejs-storage\samples\node_modules\yargs\yargs.js:1057
      else throw err
           ^

Error: This is currently not available using the Cloud Client Library.
    at Object.rotateEncryptionKey [as handler] (C:\Users\sawch\dev\nodejs-storage\samples\encryption.js:59:81)
    at Object.runCommand (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\yargs\yargs.js:970:30)
    at Object.parse (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\yargs\yargs.js:538:25)
    at Object.<anonymous> (C:\Users\sawch\dev\nodejs-storage\samples\encryption.js:60:1582)
    at Module._compile (module.js:624:30)
    at Module.replacementCompile (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module.replacementCompile (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\sawch\dev\nodejs-storage\samples\node_modules\nyc\node_modules\append-transform\index.js:62:4
  √ encryption » should rotate keys (411ms)
  √ requesterPays » should fetch requester-pays status on a modified bucket (1.1s)
  √ iam » should remove multiple members from a role on a bucket (1.6s)
  √ acl » should add a user as an owner on a bucket (1.6s)
  √ files » should move a file (1.9s)
  √ requesterPays » should download a file using requester-pays requests (1.3s)
  √ acl » should remove a user from a bucket (1.7s)
  √ requesterPays » should disable requester-pays requests (1.3s)
  √ files » should copy a file (1.8s)
  √ acl » should add a user as a default owner on a bucket (1.3s)
  √ files » should list files (1.1s)
  √ acl » should remove a default user from a bucket (1.3s)
  √ files » should list files by a prefix (2.4s)
  √ acl » should print a user's acl for a file (1.7s)
  √ files » should make a file public (1.3s)
  √ acl » should add a user as an owner on a bucket (1.3s)
  √ files » should generate a signed URL for a file (797ms)
  √ acl » should remove a user from a bucket (1.3s)
  √ files » should get metadata for a file (1s)
  √ acl » should print acl for a bucket (1.1s)
  √ acl » should print acl for a file (1.2s)
  √ files » should delete a file (1.2s)
{ Error: ENOENT: no such file or directory, unlink 'C:\Users\sawch\dev\nodejs-storage\samples\resources\downloaded.txt'
    at Object.fs.unlinkSync (fs.js:1068:18)
    at Test.test.after.always [as fn] (C:\Users\sawch\dev\nodejs-storage\samples\system-test\files.test.js:42:8)
    at Test.callFn (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\test.js:305:18)
    at Test.run (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\test.js:318:23)
    at runNext (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\sequence.js:58:44)
    at Sequence.run (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\sequence.js:90:10)
    at runNext (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\sequence.js:58:44)
    at promise.then.passed (C:\Users\sawch\dev\nodejs-storage\samples\node_modules\ava\lib\sequence.js:86:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt' }

  4 tests failed [16:43:52]
  1 test skipped

  encryption » should upload a file

  C:\Users\sawch\dev\nodejs-storage\samples\system-test\encryption.test.js:79

   78:   );
   79:   t.regex(
   80:     results.stdout + results.stderr,

  Value must match expression:

  'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.null'

  Regular expression:

  /File C:\Users\sawch\dev\nodejs-storage\samples\resources\test.txt uploaded to gs:\/\/nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f\/test.txt./

  results.stdout+results.stderr
  => 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.null'

  results.stderr
  => null

  results
  => {
    err: null,
    output: 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.',
    stderr: null,
    stdout: 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.',
  }

  results.stdout
  => 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.'

  results
  => {
    err: null,
    output: 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.',
    stderr: null,
    stdout: 'File C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to gs://nodejs-storage-samples-245817c2-d946-4509-b149-3c423d5c219f/test.txt.',
  }



  encryption » should download a file

  C:\Users\sawch\dev\nodejs-storage\samples\system-test\encryption.test.js:92

   91:   );
   92:   t.regex(
   93:     results.stdout + results.stderr,

  Value must match expression:

  'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.null'

  Regular expression:

  /File test.txt downloaded to C:\Users\sawch\dev\nodejs-storage\samples\resources\downloaded.txt./

  results.stdout+results.stderr
  => 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.null'

  results.stderr
  => null

  results
  => {
    err: null,
    output: 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
    stderr: null,
    stdout: 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
  }

  results.stdout
  => 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.'

  results
  => {
    err: null,
    output: 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
    stderr: null,
    stdout: 'File test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
  }



  files » should upload a file

  C:\Users\sawch\dev\nodejs-storage\samples\system-test\files.test.js:66

   65:   );
   66:   t.regex(
   67:     results.stdout + results.stderr,

  Value must match expression:

  'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.null'

  Regular expression:

  /C:\Users\sawch\dev\nodejs-storage\samples\resources\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8./

  results.stdout+results.stderr
  => 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.null'

  results.stderr
  => null

  results
  => {
    err: null,
    output: 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.',
    stderr: null,
    stdout: 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.',
  }

  results.stdout
  => 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.'

  results
  => {
    err: null,
    output: 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.',
    stderr: null,
    stdout: 'C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\test.txt uploaded to nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8.',
  }



  files » should download a file

  C:\Users\sawch\dev\nodejs-storage\samples\system-test\files.test.js:79

   78:   );
   79:   t.regex(
   80:     results.stdout + results.stderr,

  Value must match expression:

  'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.null'

  Regular expression:

  /gs:\/\/nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8\/test.txt downloaded to C:\Users\sawch\dev\nodejs-storage\samples\resources\downloaded.txt./

  results.stdout+results.stderr
  => 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.null'

  results.stderr
  => null

  results
  => {
    err: null,
    output: 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
    stderr: null,
    stdout: 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
  }

  results.stdout
  => 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.'

  results
  => {
    err: null,
    output: 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
    stderr: null,
    stdout: 'gs://nodejs-storage-samples-4c87f769-65ce-4ae2-8430-5fc286a304f8/test.txt downloaded to C:\\Users\\sawch\\dev\\nodejs-storage\\samples\\resources\\downloaded.txt.',
  }


npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\8.6.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "run" "cover"
npm ERR! node v8.6.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @google-cloud/storage-samples@0.0.1 cover: `nyc --reporter=lcov --cache ava -T 20s --verbose system-test/*.test.js && nyc report`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @google-cloud/storage-samples@0.0.1 cover script 'nyc --reporter=lcov --cache ava -T 20s --verbose system-test/*.test.js && nyc report'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @google-cloud/storage-samples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nyc --reporter=lcov --cache ava -T 20s --verbose system-test/*.test.js && nyc report
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @google-cloud/storage-samples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @google-cloud/storage-samples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sawch\dev\nodejs-storage\samples\npm-debug.log
run: Oh no! Test failed after 28.0s.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/storage-samples@0.0.1 test: `repo-tools test run --cmd npm -- run cover`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @google-cloud/storage-samples@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sawch\AppData\Roaming\npm-cache\_logs\2017-10-09T20_43_53_317Z-debug.log
```

**Comment by jmdobry** [comment]
I just tried it, I got:

```
36 tests passed [14:59:55]
  1 test skipped
  1 uncaught exception
```

`bucket.notification` is not available because the samples are pinned to a particular version of `@google-cloud/storage`. I then did the following to get it to work:

```
cd ..
npm link
cd samples
npm link @google-cloud/storage
npm test
```

and I got

```
40 tests passed [15:01:24]
  1 test skipped
```

**Comment by callmehiphop** [comment]
FWIW I get the same errors as Stephen, is it possible we are missing a setup step?

**Comment by jmdobry** [comment]
This is what I did:

1. `git clone git@github.com:googleapis/nodejs-storage.git`
1. `cd nodejs-storage`
1. `npm install`
1. `cd samples`
1. `npm install`
1. `npm link ../`
1. `GCLOUD_PROJECT=my-project-id GOOGLE_APPLICATION_CREDENTIALS=/path/to/keyfile.json npm test`

**Comment by stephenplusplus** [comment]
Same process errors for me.

**Comment by jmdobry** [comment]
I used Node v6.11.1 and MacOS, what about y'all?

**Comment by callmehiphop** [comment]
I've been messing with this a little bit and it seems like the `File#download` test fails intermittently. However when it does pass, everything passes for me.

**Comment by jmdobry** [comment]
So possibly a flaky test issue.
