### ISSUE TITLE
Property name expected type of string but got null

### ISSUE THREAD

**Issue by VolkerSchiewe** [googleapis/nodejs-storage#576]
### Environment details
* OS: macOS 10.14.2
* Node.js version: v11.6.0
* npm version: 6.5.0-next.0
* `@google-cloud/storage` version: 2.3.4
#### tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": false,
    "noUnusedLocals": false,
    "newLine": "lf",
    "module": "commonjs",
    "target": "es6",
    "jsx": "react"
  },
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "./node_modules"
  ]
}
```
### Steps to reproduce
1. Create a simple React-Typescript Webapp bundled with Parcel.js
2. Add `@google-cloud/storage` to dependencies and use it somewhere.
3. Parcel build process crashes

#### Error Message
```
/Users/volker/Projects/ossi/client/node_modules/google-auth-library/build/src/auth/jwtclient.js: Property name expected type of string but got null
    at validate (/Users/volker/Projects/ossi/client/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/Users/volker/Projects/ossi/client/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/Users/volker/Projects/ossi/client/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/volker/Projects/ossi/client/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.Identifier (/Users/volker/Projects/ossi/client/node_modules/@babel/types/lib/builders/generated/index.js:317:31)
    at /Users/volker/Projects/ossi/client/node_modules/regenerator-transform/lib/hoist.js:30:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/Users/volker/Projects/ossi/client/node_modules/regenerator-transform/lib/hoist.js:27:23)
    at exit (/Users/volker/Projects/ossi/client/node_modules/regenerator-transform/lib/hoist.js:46:20)
    at NodePath._call (/Users/volker/Projects/ossi/client/node_modules/@babel/traverse/lib/path/context.js:53:20)

```

### Additional Information
* No Problems if the code is executed by jest or ts-node

**Comment by JustinBeckwith** [comment]
Greetings!  We recently made some changes to the underlying auth libraries to better support webpack/parcel.  Could you give this another try?

**Comment by JustinBeckwith** [comment]
Greetings @VolkerSchiewe!  If you're still running into issues - please do let us know.  We're going to close this out for now.

**Comment by johntran** [comment]
@JustinBeckwith I'm getting this error with `"@google-cloud/storage": "2.5.0"`. Any advice?
