### ISSUE TITLE
supertest and gaxios do not work in conjunction

### ISSUE THREAD

**Issue by VikramTiwari** [googleapis/nodejs-storage#730]
#### Environment details

  - OS: Mac OS X - 10.14.5
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/storage` version: 2.5.0

#### Steps to reproduce

  1. Using supertest to test an endpoint which runs the following code and return the files as response.

```
const [files] = await storage
            .bucket(bucketName)
            .getFiles({
              prefix: String(user._id),
            })
```
  2. While running the endpoint as normal server and sending requests, it works fine. But while running test, it breaks.
  3. Confirming that all the config, auth and service account credentials etc are properly set in test environment as well

Error log:
```
    TypeError: fetch is not a function

      at Gaxios.<anonymous> (node_modules/gaxios/src/gaxios.ts:70:27)
      at node_modules/gaxios/build/src/gaxios.js:19:71
      at Object.<anonymous>.__awaiter (node_modules/gaxios/build/src/gaxios.js:15:12)
      at Gaxios.request (node_modules/gaxios/build/src/gaxios.js:60:16)
      at Object.<anonymous> (node_modules/gaxios/src/index.ts:31:19)
      at node_modules/gaxios/build/src/index.js:19:71
      at Object.<anonymous>.__awaiter (node_modules/gaxios/build/src/index.js:15:12)
      at Object.request (node_modules/gaxios/build/src/index.js:37:12)
      at GoogleToken.<anonymous> (node_modules/gtoken/build/src/index.js:191:29)
      at node_modules/gtoken/build/src/index.js:13:71
      at Object.<anonymous>.__awaiter (node_modules/gtoken/build/src/index.js:9:12)
      at GoogleToken.requestToken (node_modules/gtoken/build/src/index.js:179:16)
      at GoogleToken.<anonymous> (node_modules/gtoken/build/src/index.js:125:25)
      at node_modules/gtoken/build/src/index.js:13:71
      at Object.<anonymous>.__awaiter (node_modules/gtoken/build/src/index.js:9:12)
      at GoogleToken.getTokenAsync (node_modules/gtoken/build/src/index.js:110:16)
      at GoogleToken.getToken (node_modules/gtoken/build/src/index.js:64:21)
      at JWT.<anonymous> (node_modules/google-auth-library/build/src/auth/jwtclient.js:144:40)
      at node_modules/google-auth-library/build/src/auth/jwtclient.js:22:71
      at Object.<anonymous>.__awaiter (node_modules/google-auth-library/build/src/auth/jwtclient.js:18:12)
      at JWT.refreshTokenNoCache (node_modules/google-auth-library/build/src/auth/jwtclient.js:142:16)
      at JWT.<anonymous> (node_modules/google-auth-library/build/src/auth/oauth2client.js:160:28)
      at node_modules/google-auth-library/build/src/auth/oauth2client.js:22:71
      at Object.<anonymous>.__awaiter (node_modules/google-auth-library/build/src/auth/oauth2client.js:18:12)
      at JWT.refreshToken (node_modules/google-auth-library/build/src/auth/oauth2client.js:151:16)
      at JWT.<anonymous> (node_modules/google-auth-library/build/src/auth/oauth2client.js:289:32)
      at node_modules/google-auth-library/build/src/auth/oauth2client.js:22:71
      at Object.<anonymous>.__awaiter (node_modules/google-auth-library/build/src/auth/oauth2client.js:18:12)
      at JWT.getRequestMetadataAsync (node_modules/google-auth-library/build/src/auth/oauth2client.js:271:16)
      at JWT.<anonymous> (node_modules/google-auth-library/build/src/auth/jwtclient.js:87:55)
      at node_modules/google-auth-library/build/src/auth/jwtclient.js:22:71
      at Object.<anonymous>.__awaiter (node_modules/google-auth-library/build/src/auth/jwtclient.js:18:12)
      at JWT.getRequestMetadataAsync (node_modules/google-auth-library/build/src/auth/jwtclient.js:70:16)
      at JWT.<anonymous> (node_modules/google-auth-library/build/src/auth/oauth2client.js:266:36)
      at node_modules/google-auth-library/build/src/auth/oauth2client.js:22:71
      at Object.<anonymous>.__awaiter (node_modules/google-auth-library/build/src/auth/oauth2client.js:18:12)
      at JWT.getRequestHeaders (node_modules/google-auth-library/build/src/auth/oauth2client.js:265:16)
      at GoogleAuth.<anonymous> (node_modules/google-auth-library/build/src/auth/googleauth.js:598:42)
      at fulfilled (node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
```

**Comment by JustinBeckwith** [comment]
Greetings!  Is there any chance you're trying to run this in the browser, via create-react-app, webpack, rollup, electron, any of that stuff?

**Comment by VikramTiwari** [comment]
Hey @JustinBeckwith No, this is just an express based API server running purely on nodejs on GAE. While it runs as server, it works fine. It's only during testing that I see this happen. Very weird. Initially I thought it was auth but checked everything with test credentials and not seeing this error happen at all.

I will keep the issue updated if I find anything.

**Comment by bcoe** [comment]
@VikramTiwari could you share the code you are executing in your `it` block in `supertest`?

If I understand correctly, you are able to manually `curl` the endpoint, but the `supertest` request fails?

**Comment by VikramTiwari** [comment]
Hey @bcoe Yes, that is correct. Here's the failing test.

```
it('Returns download urls', async () => {
    return request(app)
      .post('/')
      .send({ op: 'downloadUrls' })
      .set({
        Authorization: `Bearer ${testUser.bearerToken}`,
        Accept: 'application/json',
      })
      .expect('Content-Type', /json/)
      .expect(200)
      .then(response => {
        expect(response.body.length).toBeGreaterThan(0)
      })
  })
```

**Comment by bcoe** [comment]
@VikramTiwari nothing immediately jumps out at me (from your logic, or the stacktrace you shared initially).

It might also be worth opening an issue on the `supertest` repo, I'm wondering if perhaps a global is being overridden; resulting in `fetch` having a different value than `gaxios` expects.
