### ISSUE TITLE
'async' package still being used by bucket.js (but only present in devDependencies)

### ISSUE THREAD

**Issue by jbottigliero** [googleapis/nodejs-storage#741]
#### Environment details

  - OS: Mac OS X 10.14.3
  - Node.js version: v10.16.0
  - npm version: 6.9.0
  - `@google-cloud/storage` version: 3.0.0

#### Steps to reproduce

Reproduction File:
```js
// index.js
const {Storage} = require('@google-cloud/storage');

const storage = new Storage();
```

Output
```
$ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/joebottigliero/dev/albert-io/albert-data/data-modifications/2019-06-14-gcs-content-type/node_modu
les/@google-cloud/storage/build/src/bucket.js:22:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Taking a look a the built `bucket.js`, it looks like the `async` module is still being referenced.

Seems related to #702 – and looks like I might be one of the first to catch the new release!

**Comment by jbottigliero** [comment]
https://github.com/googleapis/nodejs-storage/blob/master/src/bucket.ts#L33 looks like it might be the cause – let me know if I can provide any additional information!

**Comment by bcoe** [comment]
@jbottigliero :wave: fancy seeing you here. Could you try the `3.0.1` version of the module? released a hot fix with `async` in `dependencies`.

**Comment by bcoe** [comment]
I've confirmed that `3.0.0` exists with an exception (due to the missing `async`) and `3.0.1` healthy.

Thanks for the report @jbottigliero, let me know if you bump into any more issues; I'll also be kicking around this weekend doing some OSS work I expect.

**Comment by jbottigliero** [comment]
@bcoe – just had a chance to verify myself... thanks for the follow-up and I'll see you "around" – I appreciate the quick turn-around by you and the team!
