### ISSUE TITLE
Error about billing account when trying to push to unowned, but most likely created bucket

### ISSUE THREAD

**Issue by shaunwarman** [googleapis/nodejs-storage#769]
I simply tried to hit a bucket that I did not own, but was most likely created (e.g. bucket name `testing123`). I notice the message: `Error: The project to be billed is associated with an absent billing account.`. Stack trace below.

I guess this is expected since buckets are under a global namespace. But this may lead to a bit of confusion.

```
Error: The project to be billed is associated with an absent billing account.
    at Util.parseHttpRespBody (/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:191:38)
    at Util.handleResp (/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at retryRequest (/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/build/src/util.js:423:22)
    at onResponse (/node_modules/retry-request/index.js:206:7)
    at /node_modules/teeny-request/build/src/index.js:158:17
```

**Comment by AVaksman** [comment]
The error means that there is a project that user has authorization to. The project is no longer connected to an active (billable) account, so the cost for the project cannot be charged. Probably the account got cancelled or suspended. When user is trying an operation that costs money this error will be returned.

**Comment by AVaksman** [comment]
I am closing this issue.
If you have any more questions, please feel free to reopen this issue.
