### ISSUE TITLE
Fail with error: URL is required on resumable upload

### ISSUE THREAD

**Issue by jiren** [googleapis/nodejs-storage#811]
Error while resumable upload due to metadata size.
The original error is metadata size but some issue in gcd-resumable, due to issue  in gcd-resumable upload not able to write entry URI field in `~/.config/configstore/gcs-resumable-upload.json`. 

```
Error: URL is required.
    at Gaxios.validateOpts (/home/nodejs-storage/node_modules/gaxios/build/src/gaxios.js:111:19)
    at Gaxios.request (/home/nodejs-storage/node_modules/gaxios/build/src/gaxios.js:58:21)
    at Object.request (/home/nodejs-storage/node_modules/gaxios/build/src/index.js:29:29)
    at DefaultTransporter.request (/home/nodejs-storage/node_modules/google-auth-library/build/src/transporters.js:65:29)
    at JWT.requestAsync (/home/nodejs-storage/node_modules/google-auth-library/build/src/auth/oauth2client.js:346:41)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Here is the content  of `~/.config/configstore/gcs-resumable-upload.json`
```json
{
  "fe-store/1.txt": {
    "txt": {
      "firstChunk": {
        "type": "Buffer",
        "data": [
          116,
          101,
          115,
          116
        ]
      }
    }
  }
}
```

#### Environment details

  - OS: os x
  - Node.js version: 11.1.0
  - npm version: 6.9.2
  - `@google-cloud/storage` version:  3.1.0

#### Steps to reproduce

  https://gist.github.com/jiren/2d6dec5b42f9c8559837339c3b0232e7

**Comment by stephenplusplus** [comment]
I've sent a PR to fix this on gcs-resumable-upload: https://github.com/googleapis/gcs-resumable-upload/pull/255

**Comment by stephenplusplus** [comment]
Fix merged! Just need a release of gcs-resumable-upload, then we will update here.

**Comment by stephenplusplus** [comment]
New installations of Storage should pick up the underlying change made in gcs-resumable-upload.
