### ISSUE TITLE
Pumpify.Deplexify.end Error

### ISSUE THREAD

**Issue by gauntface** [googleapis/nodejs-storage#84]
Version ^1.2.1

I keep getting this error when trying to load files to Cloud Storage:

```
TypeError: Cannot read property 'ending' of undefined
    at Pumpify.Duplexify.end (/home/matt/Projects/Code/workbox/node_modules/duplexify/index.js:224:28)
    at Pumpify.Duplexify.setWritable (/home/matt/Projects/Code/workbox/node_modules/duplexify/index.js:82:10)
    at Pumpify.setPipeline (/home/matt/Projects/Code/workbox/node_modules/pumpify/index.js:47:10)
    at new Pumpify (/home/matt/Projects/Code/workbox/node_modules/pumpify/index.js:15:30)
    at Pumpify (/home/matt/Projects/Code/workbox/node_modules/pumpify/index.js:13:44)
    at File.createWriteStream (/home/matt/Projects/Code/workbox/node_modules/@google-cloud/storage/src/file.js:915:5)
    at upload (/home/matt/Projects/Code/workbox/node_modules/@google-cloud/storage/src/bucket.js:2236:21)
    at /home/matt/Projects/Code/workbox/node_modules/@google-cloud/storage/src/bucket.js:2229:7
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by stephenplusplus** [comment]
Can you show repro code?

**Comment by gauntface** [comment]
Relevant code is: https://github.com/GoogleChrome/workbox/blob/v3/gulp-tasks/utils/cdn-helper.js

**Comment by stephenplusplus** [comment]
Is this still a problem? Can you try the latest version?
