### ISSUE TITLE
UnhandledPromiseRejection when deleting an object that doesn't exist in a bucket

### ISSUE THREAD

**Issue by ragrag** [googleapis/nodejs-storage#867]
Receiving UnhandledPromiseRejection when deleting an object that doesn't exist in a bucket 
```js
  async deleteByName(imageName) {
    try {
      await this.storage
        .bucket('this-or-that')
        .file(imageName)
        .delete();
    } catch (err) {
      throw err;
    }
  }
```
Calling this method with an object that doesn't exist produces

```
(node:17744) UnhandledPromiseRejectionWarning: Error: No such object: this-or-that/user5d8f564fc428814550deee2c
    at new ApiError (G:\Projects\nodejs\this-or-that\node_modules\@google-cloud\common\build\src\util.js:60:15)
    at Util.parseHttpRespBody (G:\Projects\nodejs\this-or-that\node_modules\@google-cloud\common\build\src\util.js:195:38)
    at Util.handleResp (G:\Projects\nodejs\this-or-that\node_modules\@google-cloud\common\build\src\util.js:136:117)
    at retryRequest (G:\Projects\nodejs\this-or-that\node_modules\@google-cloud\common\build\src\util.js:431:22)
    at onResponse (G:\Projects\nodejs\this-or-that\node_modules\retry-request\index.js:206:7)
    at G:\Projects\nodejs\this-or-that\node_modules\teeny-request\build\src\index.js:256:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
```
#### Environment details

  - OS: Windows 10 64bit
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/storage` version: 3.3.0

**Comment by bcoe** [comment]
@jkwlui seems like something worth digging in to, wasn't sure if we should label as a `p1`.

**Comment by stephenplusplus** [comment]
Hey @ragrag 👋. Using the same Storage version, I was able to catch and log the error:

```js
'use strict'

const {Storage} = require('@google-cloud/storage')
const storage = new Storage()
const file = storage.bucket(process.env.BUCKET_NAME).file('non-existent-file')

;(async() => {
  try {
    await file.delete()
  } catch (e) {
    console.log('I caught this!', e.message)
  }
})()
```

Would you be able to try this out? (Feel free to edit the bucket name directly, or set the `BUCKET_NAME` environment variable.

My output:
```
$ node .
I caught this! No such object: stephen-has-a-new-bucket/non-existent-file
```

**Comment by ragrag** [comment]
Hello @stephenplusplus,
Thank you for your time, upon checking your code and re-examining mine, seems like the problem was in my code invoking this function without awaiting it so it escapes the catch block. 

All works fine now, thank you and sorry for any inconveniences 😅

**Comment by stephenplusplus** [comment]
No problem, glad to hear it's working!

**Comment by saran141998** [comment]
````


  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage();

  const myBucket=storage.bucket(process.env.BUCKET_NAME);

  const file=myBucket.file(filename);

    file.download(async function(err, contents) {});


    file.download({
      destination: '/home/saravanan/Downloads'
    }, function(err) {});
    
    
    file.download().then(function(data) {
      const contents = data[0];
    });

  While i tried to download the file in firebase storage using the above function I got this error

(node:9011) UnhandledPromiseRejectionWarning: Error: No such object: vintro-functions.appspot.com/920221923111532725.pdf
    at new ApiError (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespMessage (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:160:41)
    at Util.handleResp (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/common/build/src/util.js:134:76)
    at Duplexify.requestStream.on.on.res (/home/saravanan/Projects/download-test/functions/node_modules/@google-cloud/storage/build/src/file.js:830:31)
    at Duplexify.emit (events.js:198:13)
    at DestroyableTransform.emit (events.js:198:13)
    at onResponse (/home/saravanan/Projects/download-test/functions/node_modules/retry-request/index.js:200:19)
    at PassThrough.<anonymous> (/home/saravanan/Projects/download-test/functions/node_modules/retry-request/index.js:152:11)
    at PassThrough.emit (events.js:203:15)
    at /home/saravanan/Projects/download-test/functions/node_modules/teeny-request/build/src/index.js:201:29
(node:9011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
